// Help entries for the Audio Toolbox, extracted from audio.ts.
// Keyed by function name; consumed via ToolboxModule.help (see tb/types.ts).
import type { HelpEntry } from './types';

export const HELP_AUDIO: Record<string, HelpEntry | string> = {
    hz2bark: { summary: 'Converts values in hertz to values on the Bark frequency scale.', syntax: ['bark = hz2bark(hz)'], seealso: ['bark2hz', 'hz2mel', 'mel2hz', 'hz2erb', 'erb2hz'], description: ['bark = hz2bark(hz) converts values in hertz to values on the Bark frequency scale.'] },
    bark2hz: { summary: 'Converts values on the Bark frequency scale to values in hertz.', syntax: ['hz = bark2hz(bark)'], seealso: ['hz2bark', 'hz2mel', 'mel2hz', 'hz2erb', 'erb2hz'], description: ['hz = bark2hz(bark) converts values on the Bark frequency scale to values in hertz.'] },
    hz2mel: { summary: 'Converts values in hertz to values on the mel frequency scale.', syntax: ['mel = hz2mel(hz)', 'mel = hz2mel(hz,MelStyle=style)'], seealso: ['mel2hz', 'hz2erb', 'erb2hz', 'hz2bark', 'bark2hz'], description: ['mel = hz2mel(hz) converts values in hertz to values on the mel frequency scale.', 'mel = hz2mel(hz,MelStyle=style) specifies whether to use the Slaney- style or O\'Shaughnessy-style mel scale.'] },
    mel2hz: { summary: 'Converts values on the mel frequency scale to values in hertz.', syntax: ['hz = mel2hz(mel)', 'hz = mel2hz(mel,MelStyle=style)'], seealso: ['hz2mel', 'hz2erb', 'erb2hz', 'hz2bark', 'bark2hz'], description: ['hz = mel2hz(mel) converts values on the mel frequency scale to values in hertz.', 'hz = mel2hz(mel,MelStyle=style) specifies whether to use the Slaney- style or O\'Shaughnessy-style mel scale.'] },
    hz2erb: { summary: 'Converts values in hertz to values on the ERB frequency scale.', syntax: ['erb = hz2erb(hz)'], seealso: ['erb2hz', 'hz2mel', 'mel2hz', 'hz2bark', 'bark2hz'], description: ['erb = hz2erb(hz) converts values in hertz to values on the ERB frequency scale.'] },
    erb2hz: { summary: 'Converts values on the ERB frequency scale to values in hertz.', syntax: ['hz = erb2hz(erb)'], seealso: ['hz2erb', 'hz2mel', 'mel2hz', 'hz2bark', 'bark2hz'], description: ['hz = erb2hz(erb) converts values on the ERB frequency scale to values in hertz.'] },
    dBov: { summary: 'Convert linear amplitude to dBov (full-scale decibels)', syntax: ['dBov_val = dBov(x)'], seealso: ['mag2db', 'db2mag'], description: ['Lmean = dBov(audioIn) returns the average Decibel-to-overload signal level (dBov), Lmean, for the input signal, audioIn, according to the algorithms defined in the ITU-T Recommendation G.100.1 standard .', 'Lmean = dBov(audioIn,ClippingMagnitude=Lclip) additionally specifies the clipping (overload) amplitude, Lclip.', '[Lmean,Lpeak] = dBov(___) additionally returns Lpeak, which is the peak decibel to overload signal level.'] },
    phon2sone: { summary: 'Converts phon to sone, according to ISO 532-1:2017(E).', syntax: ['sone = phon2sone(phon)', 'sone = phon2sone(phon,standard)'], seealso: ['sone2phon', 'acousticLoudness'], description: ['sone = phon2sone(phon) converts phon to sone, according to ISO 532-1:2017(E).', 'sone = phon2sone(phon,standard) specifies the standard used to convert phon to sone.'] },
    sone2phon: { summary: 'Converts sone to phon, according to ISO 532-1:2017(E).', syntax: ['phon = sone2phon(sone)', 'phon = sone2phon(sone,standard)'], seealso: ['phon2sone', 'acousticLoudness'], description: ['phon = sone2phon(sone) converts sone to phon, according to ISO 532-1:2017(E).', 'phon = sone2phon(sone,standard) specifies the standard used to convert sone to phon.'] },
    octavebw2bw: { summary: 'Converts octave bandwidths N and band center frequencies fc into linear analog cutoff frequencies cutoffsAnalog.', syntax: ['cutoffsAnalog = octavebw2bw(N,fc)', '[cutoffsAnalog,cutoffsDigital] = octavebw2bw(N,fc,SampleRate=fs)'], seealso: ['q2octavebw', 'octavebw2q', 'bw2octavebw', 'audioBandwidthSpecification'], description: ['cutoffsAnalog = octavebw2bw(N,fc) converts octave bandwidths N and band center frequencies fc into linear analog cutoff frequencies cutoffsAnalog.', '[cutoffsAnalog,cutoffsDigital] = octavebw2bw(N,fc,SampleRate=fs) returns the digital cutoff frequency cutoffsDigital when you specify a sample rate using SampleRate=fs.'] },
    bw2octavebw: { summary: 'Converts cutoff frequencies into octave bandwidths, N.', syntax: ['[N,FcAnalog] = bw2octavebw(CutoffFrequencies)', '[N,FcAnalog,FcDigital] = bw2octavebw(CutoffFrequencies,SampleRate=fs)'], seealso: ['q2octavebw', 'octavebw2q', 'octavebw2bw', 'audioBandwidthSpecification'], description: ['[N,FcAnalog] = bw2octavebw(CutoffFrequencies) converts cutoff frequencies into octave bandwidths, N. FcAnalog are the center frequencies of the octave bands.', '[N,FcAnalog,FcDigital] = bw2octavebw(CutoffFrequencies,SampleRate=fs) returns the analog center frequencies, FcAnalog, and the digital center frequencies, FcDigital, of the octave bands when you specify a sample rate using SampleRate=fs.'] },
    mls: { summary: 'Returns an excitation signal generated using the maximum length sequence (MLS) technique.', syntax: ['excitation = mls', 'excitation = mls(L)', 'excitation = mls(L,ExcitationLevel=level)'], seealso: ['impzest', 'sweeptone'], description: ['excitation = mls returns an excitation signal generated using the maximum length sequence (MLS) technique. This type of sequence is a pseudo-random binary sequence.', 'excitation = mls(L) specifies the output length L of the excitation signal.', 'excitation = mls(L,ExcitationLevel=level) specifies the level of the excitation signal to generate in dB.'] },
  };
