// Help entries for the Bioinformatics Toolbox, extracted from bioinfo.ts.
// Keyed by function name; consumed via ToolboxModule.help (see tb/types.ts).
import type { HelpEntry } from './types';

export const HELP_BIOINFO: Record<string, HelpEntry | string> = {
    nt2int: { summary: 'Convert nucleotide sequence to integer sequence', syntax: ['SeqInt = nt2int(SeqChar)', 'SeqInt = nt2int(SeqChar,Name=Value)'], description: ['SeqInt = nt2int(SeqChar) converts a nucleotide character sequence to a row vector of integers using the standard IUPAC encoding (A=1, C=2, G=3, T=4, etc.).', "Specify 'Unknown' to control the integer value for unknown nucleotides (default 0); 'ACGTOnly',true to restrict to A/C/G/T/U only."], seealso: ['int2nt', 'aa2int', 'baselookup'] },
    int2nt: { summary: 'Convert integer sequence to nucleotide sequence', syntax: ['SeqChar = int2nt(SeqInt)', 'SeqChar = int2nt(SeqInt,Name=Value)'], description: ["SeqChar = int2nt(SeqInt) converts an integer vector to a nucleotide character vector using the standard IUPAC decoding.", "Specify 'Alphabet','DNA' (default) or 'RNA' to choose the nucleotide alphabet."], seealso: ['nt2int', 'int2aa', 'baselookup'] },
    aa2int: { summary: 'Convert amino acid sequence to integer sequence', syntax: ['SeqInt = aa2int(SeqChar)', 'SeqInt = aa2int(SeqChar,Unknown=unknownAA)'], description: ['SeqInt = aa2int(SeqChar) converts a character vector or string of single-letter amino acid codes to a row vector of integers.'], seealso: ['int2aa', 'nt2int', 'aminolookup'] },
    int2aa: { summary: 'Convert integer sequence to amino acid sequence', syntax: ['SeqChar = int2aa(SeqInt)', 'SeqChar = int2aa(SeqInt,Name=Value)'], description: ['SeqChar = int2aa(SeqInt) converts an integer vector to a character vector of single-letter amino acid codes.'], seealso: ['aa2int', 'int2nt', 'aminolookup'] },
    seqreverse: { summary: 'Reverse a nucleotide sequence', syntax: ['SeqR = seqreverse(SeqNT)'], seealso: ['seqcomplement', 'seqrcomplement', 'fliplr'], description: ['_SeqR_ = seqreverse(_SeqNT_) calculates the reverse strand of a DNA or RNA nucleotide sequence. The return sequence, _SeqR_ , reads from 3\' --> 5\' and is in the same format as _SeqNT_. For example, if _SeqNT_ is a vector of integers, then so is _SeqR_.'] },
    seqcomplement: { summary: 'Complementary strand of a DNA/RNA nucleotide sequence', syntax: ['SeqC = seqcomplement(SeqNT)'], seealso: ['seqrcomplement', 'seqreverse', 'palindromes'], description: ['SeqC = seqcomplement(SeqNT) returns the complementary sequence of the DNA or RNA nucleotide sequence contained in SeqNT. The format of SeqC matches SeqNT. For example, if SeqNT is a vector of integers, then so is SeqC. For complementary base pairs, see Complementary DNA and RNA Base Pairs. For complementary ambiguous characters, see Complementary IUPAC Ambiguity Codes.'] },
    seqrcomplement: { summary: 'Reverse complement of a DNA/RNA nucleotide sequence', syntax: ['SeqRC = seqrcomplement(SeqNT)'], seealso: ['seqcomplement', 'seqreverse'], description: ['SeqRC = seqrcomplement(arguSeqNT) calculates the reverse complementary strand of a DNA or RNA nucleotide sequence. The return sequence, SeqRC, reads from 3\' to 5\' and is in the same format as SeqNT. For example, if SeqNT is a vector of integers, then so is SeqRC.'] },
    basecount: { summary: 'Count nucleotide base occurrences in a sequence', syntax: ['NTStruct = basecount(SeqNT)', 'NTStruct = basecount(SeqNT,Name=Value)'], seealso: ['aacount', 'codoncount', 'dimercount', 'baselookup'], description: ['NTStruct = basecount(SeqNT) returns the number of each type of base in SeqNT.', 'NTStruct = basecount(SeqNT,Name=Value) uses additional options specified by one or more name-value arguments.'] },
    aacount: { summary: 'Count amino acid occurrences in a sequence', syntax: ['countStruct = aacount(SeqAA)', 'countStruct = aacount(SeqAA,Name=Value)'], seealso: ['basecount', 'codoncount', 'aminolookup'], description: ['countStruct = aacount(SeqAA) counts the number of each type of amino acid in SeqAA, an amino acid sequence, and returns the counts in countStruct, a 1-by-1 MATLAB® structure containing fields for the standard 20 amino acids (A, R, N, D, C, Q, E, G, H, I, L, K, M, F, P, S, T, W, Y, and V).', 'countStruct = aacount(SeqAA,Name=Value) uses additional options specified by one or more name-value arguments. For example, countStruct = aacount(SeqAA,Chart="pie") creates a pie chart showing relative proportions of the amino acids.'] },
    nt2aa: { summary: 'Convert nucleotide sequence to amino acid sequence', syntax: ['SeqAA = nt2aa(SeqNT)', 'SeqAA = nt2aa(SeqNT,Name=Value)'], description: ['SeqAA = nt2aa(SeqNT) translates a nucleotide sequence to an amino acid sequence using the standard genetic code.'], seealso: ['aa2nt', 'baselookup', 'codonbias'] },
  };
