// Help entries for the Econometrics Toolbox, extracted from econ.ts.
// Keyed by function name; consumed via ToolboxModule.help (see tb/types.ts).
import type { HelpEntry } from './types';

export const HELP_ECON: Record<string, HelpEntry | string> = {
    adftest: { summary: 'Returns the rejection decision from conducting an augmented Dickey-Fuller test for a unit root in the input univariate time series.', syntax: ['h = adftest(y)', 'StatTbl = adftest(Tbl)'], seealso: ['kpsstest', 'lmctest', 'pptest', 'vratiotest', 'i10test'], description: ['h = adftest(y) returns the rejection decision from conducting an augmented Dickey-Fuller test for a unit root in the input univariate time series.'] },
    pptest: { summary: 'Returns the rejection decision from conducting the Phillips-Perron test for a unit root in the input univariate time series.', syntax: ['h = pptest(y)', 'StatTbl = pptest(Tbl)'], seealso: ['adftest', 'kpsstest', 'vratiotest', 'lmctest'], description: ['h = pptest(y) returns the rejection decision from conducting the Phillips-Perron test for a unit root in the input univariate time series.'] },
    price2ret: { summary: 'Returns the matrix of numVars continuously compounded return series, and corresponding time intervals, from the input matrix of numVars price series.', syntax: ['[Returns,intervals] = price2ret(Prices)', 'ReturnTbl = price2ret(PriceTbl)'], seealso: ['ret2price', 'tick2ret'], description: ['[Returns,intervals] = price2ret(Prices) returns the matrix of numVars continuously compounded return series, and corresponding time intervals, from the input matrix of numVars price series.'] },
    tick2ret: { summary: 'Convert tick (price) series to return series', syntax: ['ret = tick2ret(price)', 'ret = tick2ret(price,base)'], seealso: ['ret2tick', 'price2ret'] },
    lagmatrix: { summary: 'Shifts the input regular series in time by the input vector of lags (positive) or leads (negative), and returns the matrix of shifted series.', syntax: ['YLag = lagmatrix(Y,lags)', '[YLag,TLag] = lagmatrix(Y,lags)'], description: ['YLag = lagmatrix(Y,lags) shifts the input regular series in time by the input vector of lags (positive) or leads (negative), and returns the matrix of shifted series.'] },
    autocorr: { summary: 'Returns the sample autocorrelation function (ACF) and associated lags of the input univariate time series.', syntax: ['[acf,lags] = autocorr(y)', 'ACFTbl = autocorr(Tbl)'], description: ['[acf,lags] = autocorr(y) returns the sample autocorrelation function (ACF) and associated lags of the input univariate time series.'] },
  };
