// Help entries for the Radar Toolbox, extracted from radar.ts.
// Keyed by function name; consumed via ToolboxModule.help (see tb/types.ts).
import type { HelpEntry } from './types';

export const HELP_RADAR: Record<string, HelpEntry | string> = {
    dop2speed: { summary: 'Convert Doppler shift to speed', syntax: ['speed = dop2speed(dop,lambda)'], seealso: ['speed2dop', 'range2time'] },
    speed2dop: { summary: 'Convert speed to Doppler shift', syntax: ['dop = speed2dop(speed,lambda)'], seealso: ['dop2speed', 'radareqsnr'] },
    range2time: { summary: 'Convert range to propagation time', syntax: ['t = range2time(rng)', 't = range2time(rng,propspeed)'], seealso: ['time2range', 'range2bw'] },
    time2range: { summary: 'Convert propagation time to range', syntax: ['rng = time2range(t)', 'rng = time2range(t,propspeed)'], seealso: ['range2time', 'radareqrng'] },
    range2bw: { summary: 'Convert range resolution to bandwidth', syntax: ['bw = range2bw(rangeres)', 'bw = range2bw(rangeres,propspeed)'], seealso: ['range2time', 'radareqrng'] },
    radareqsnr: { summary: 'Estimates the output signal-to-noise ratio, SNR, at the receiver based on the wavelength lambda, the range tgtrng, the peak transmit power Pt, and the pulse width tau.', syntax: ['SNR = radareqsnr(lambda,tgtrng,Pt,tau)', 'SNR = radareqsnr(lambda,tgtrng,Pt,tau,Name,Value)'], seealso: ['phased.Transmitter', 'phased.ReceiverPreamp', 'noisepow', 'radareqpow', 'radareqrng'], description: ['SNR = radareqsnr(lambda,tgtrng,Pt,tau) estimates the output signal-to-noise ratio, SNR, at the receiver based on the wavelength lambda, the range tgtrng, the peak transmit power Pt, and the pulse width tau.', 'SNR = radareqsnr(lambda,tgtrng,Pt,tau,Name,Value) estimates the output SNR at the receiver with additional options specified by one or more Name,Value pair arguments.'] },
    radareqpow: { summary: 'Estimates the peak transmit power, Pt, required for a radar operating at a wavelength of lambda meters to achieve the specified signal-to-noise ratio, SNR, in decibels for a targe', syntax: ['Pt = radareqpow(lambda,tgtrng,SNR,tau)', 'Pt = radareqpow(lambda,tgtrng,SNR,tau,Name,Value)'], seealso: ['phased.Transmitter', 'phased.ReceiverPreamp', 'noisepow', 'radareqrng', 'radareqsnr'], description: ['Pt = radareqpow(lambda,tgtrng,SNR,tau) estimates the peak transmit power, Pt, required for a radar operating at a wavelength of lambda meters to achieve the specified signal-to-noise ratio, SNR, in decibels for a target at a range of tgtrng meters. tau is the pulse width. The target has a nonfluctuating radar cross section (RCS) of 1 square meter.', 'Pt = radareqpow(lambda,tgtrng,SNR,tau,Name,Value) estimates the required peak transmit power with additional options specified by one or more Name,Value pair arguments.'] },
    radareqrng: { summary: 'Estimates the theoretical maximum detectable range maxrng for a radar operating with a wavelength of lambda meters with a pulse duration of Tau seconds.', syntax: ['maxrng = radareqrng(lambda,SNR,Pt,tau)', 'maxrng = radareqrng(lambda,SNR,Pt,tau,Name,Value)'], seealso: ['phased.Transmitter', 'phased.ReceiverPreamp', 'noisepow', 'radareqpow', 'radareqsnr'], description: ['maxrng = radareqrng(lambda,SNR,Pt,tau) estimates the theoretical maximum detectable range maxrng for a radar operating with a wavelength of lambda meters with a pulse duration of Tau seconds. The signal-to-noise ratio is SNR decibels, and the peak transmit power is Pt watts.', 'maxrng = radareqrng(lambda,SNR,Pt,tau,Name,Value) estimates the theoretical maximum detectable range with additional options specified by one or more Name,Value pair arguments.'] },
    aperture2gain: { summary: 'Returns the antenna gain GdB corresponding to an effective aperture A for an incident electromagnetic wave with wavelength lambda.', syntax: ['GdB = aperture2gain(A,lambda)'], seealso: ['gain2aperture'], description: ['GdB = aperture2gain(A,lambda) returns the antenna gain GdB corresponding to an effective aperture A for an incident electromagnetic wave with wavelength lambda.'] },
    grnd2slantrange: { summary: 'Returns the slant range slrng corresponding to the ground range projection grndrng.', syntax: ['slrng = grnd2slantrange(grndrng,grazang)'], seealso: ['rainelres', 'sarazres', 'slant2grndrange'], description: ['slrng = grnd2slantrange(grndrng,grazang) returns the slant range slrng corresponding to the ground range projection grndrng.'] },
    sarnoiserefl: { summary: 'Computes the noise equivalent reflectivity.', syntax: ['neq = sarnoiserefl(freq,freqref,imgsnr,sigmaref)', 'neq = sarnoiserefl(freq,freqref,imgsnr,sigmaref,n)'], seealso: ['radareqsarpow', 'radareqsarrng', 'radareqsarsnr', 'rainscr'], description: ['neq = sarnoiserefl(freq,freqref,imgsnr,sigmaref) computes the noise equivalent reflectivity.', 'neq = sarnoiserefl(freq,freqref,imgsnr,sigmaref,n) specifies a frequency-dependent proportionality factor that depends upon the target characteristics.'] },
    mtifactor: { summary: 'Calculates the MTI improvement factor in dB given the number of pulses in an (M - 1) delay canceler, M, the transmitted frequency, FREQ, and the pulse repetition frequency, PRF.', syntax: ['IM = mtifactor(M,FREQ,PRF)', 'IM = mtifactor(M,FREQ,PRF,Name,Value)'], seealso: ['mtiloss', 'cfarloss'], description: ['IM = mtifactor(M,FREQ,PRF) calculates the MTI improvement factor in dB given the number of pulses in an (M \\- 1) delay canceler, M, the transmitted frequency, FREQ, and the pulse repetition frequency, PRF. This syntax assumes you are using coherent processing, a clutter with mean velocity of 0 m/s, and a standard deviation in clutter spread of 2 m/s.', 'IM = mtifactor(M,FREQ,PRF,Name,Value) specifies additional options using name-value arguments. For example, IM = mtifactor(4,200e9,250,\'IsCoherent\',false) calculates the MTI improvement factor assuming you are using noncoherent MTI processing. You can specify multiple name-value arguments.'] },
    steervec: { summary: 'Compute steering vector for an array', syntax: ['sv = steervec(pos,ang)', 'sv = steervec(pos,ang,freq)'], seealso: ['aperture2gain'] },
    sarbeamcompratio: { summary: 'Computes the beam compression ratio to illuminate a scene.', syntax: ['bcr = sarbeamcompratio(r,lambda,synlen,wa)', 'bcr = sarbeamcompratio(r,lambda,synlen,wa,Name,Value)'], seealso: ['sarbeamwidth', 'sarlen'], description: ['bcr = sarbeamcompratio(r,lambda,synlen,wa) computes the beam compression ratio to illuminate a scene.', 'bcr = sarbeamcompratio(r,lambda,synlen,wa,Name,Value) specifies additional options using name-value arguments.'] },
    bistaticSurfaceReflectivityLand: { summary: 'Bistatic land surface reflectivity', syntax: ['gamma = bistaticSurfaceReflectivityLand(elev_tx,elev_rx,model)'], seealso: ['sarnoiserefl'] },
  };
