// Help entries for the Fuzzy Logic Toolbox, extracted from fuzzy.ts.
// Keyed by function name; consumed via ToolboxModule.help (see tb/types.ts).
import type { HelpEntry } from './types';

export const HELP_FUZZY: Record<string, HelpEntry | string> = {
    trimf: { summary: 'Triangular membership function', syntax: ['y = trimf(x,params)'], description: ['y = trimf(x,[a b c]) returns the degree of membership of x in a triangular fuzzy set with feet at a and c and peak at b.'], seealso: ['trapmf', 'gaussmf', 'gbellmf'] },
    trapmf: { summary: 'Trapezoidal membership function', syntax: ['y = trapmf(x,params)'], description: ['y = trapmf(x,[a b c d]) returns the degree of membership of x in a trapezoidal fuzzy set defined by parameters a <= b <= c <= d.', 'The membership is 0 for x<a or x>d, rises linearly from a to b, is 1 for b<=x<=c, and falls linearly from c to d.'], seealso: ['trimf', 'gaussmf', 'pimf'] },
    gaussmf: { summary: 'Gaussian membership function', syntax: ['y = gaussmf(x,params)'], description: ['y = gaussmf(x,[sigma c]) returns membership values using a Gaussian curve centered at c with spread sigma.'], seealso: ['gauss2mf', 'gbellmf', 'trimf'] },
    gauss2mf: { summary: 'Two-sided Gaussian membership function', syntax: ['y = gauss2mf(x,params)'], description: ['y = gauss2mf(x,[sig1 c1 sig2 c2]) combines two Gaussian curves: the left side uses sig1 and c1 (for x<=c1), the right side uses sig2 and c2 (for x>=c2).', 'This creates an asymmetric bell shape useful for modeling asymmetric fuzzy sets.'], seealso: ['gaussmf', 'gbellmf', 'sigmf'] },
    gbellmf: { summary: 'Generalized bell-shaped membership function', syntax: ['y = gbellmf(x,params)'], description: ['y = gbellmf(x,[a b c]) computes the generalized bell MF 1/(1+|(x-c)/a|^(2b)).'], seealso: ['gaussmf', 'trimf', 'trapmf'] },
    sigmf: { summary: 'Sigmoidal membership function', syntax: ['y = sigmf(x,params)'], description: ['y = sigmf(x,[a c]) returns 1/(1+exp(-a*(x-c))).', 'The parameter a controls the slope and c sets the crossover point where sigmf equals 0.5.'], seealso: ['dsigmf', 'psigmf', 'smf'] },
    dsigmf: { summary: 'Difference of two sigmoidal membership functions', syntax: ['y = dsigmf(x,params)'], description: ['y = dsigmf(x,[a1 c1 a2 c2]) returns sigmf(x,[a1,c1]) - sigmf(x,[a2,c2]).'], seealso: ['sigmf', 'psigmf', 'smf'] },
    psigmf: { summary: 'Product of two sigmoidal membership functions', syntax: ['y = psigmf(x,params)'], description: ['y = psigmf(x,[a1 c1 a2 c2]) returns sigmf(x,[a1,c1]) .* sigmf(x,[a2,c2]).', 'By choosing a1>0 and a2<0 with c1<c2, the result is a bell-shaped MF.'], seealso: ['sigmf', 'dsigmf', 'gauss2mf'] },
    zmf: { summary: 'Z-shaped membership function', syntax: ['y = zmf(x,params)'], description: ['y = zmf(x,[a b]) returns a spline-based Z-shaped curve with value 1 for x<=a and 0 for x>=b.'], seealso: ['smf', 'pimf', 'trapmf'] },
    smf: { summary: 'S-shaped membership function', syntax: ['y = smf(x,params)'], description: ['y = smf(x,[a b]) returns a spline-based S-shaped curve with value 0 for x<=a and 1 for x>=b.', 'It is the complement of zmf and useful for high-valued membership regions.'], seealso: ['zmf', 'pimf', 'sigmf'] },
    pimf: { summary: 'Pi-shaped membership function', syntax: ['y = pimf(x,params)'], description: ['y = pimf(x,[a b c d]) returns a bell-shaped pi curve: rises as smf on [a,b], is 1 on [b,c], and falls as zmf on [c,d].', 'It is the product smf(x,[a,b]) .* zmf(x,[c,d]).'], seealso: ['smf', 'zmf', 'trapmf'] },
    defuzz: { summary: 'Defuzzify membership function to scalar', syntax: ['out = defuzz(x,mf,type)'], description: ["out = defuzz(x,mf,type) defuzzifies the fuzzy set defined by universe x and membership values mf using method type: 'centroid', 'bisector', 'mom', 'som', or 'lom'."], seealso: ['trimf', 'gaussmf', 'evalfis'] },
  };
