// Help entries for the Wavelet Toolbox, extracted from wavelet.ts.
// Keyed by function name; consumed via ToolboxModule.help (see tb/types.ts).
import type { HelpEntry } from './types';

export const HELP_WAVELET: Record<string, HelpEntry | string> = {
    dct: { summary: 'Discrete cosine transform', syntax: ['y = dct(x)', 'y = dct(x,n)'], seealso: ['idct', 'fft'] },
    dwt: { summary: 'Single-level 1-D discrete wavelet transform', syntax: ['[cA,cD] = dwt(x,wname)', '[cA,cD] = dwt(x,Lo_D,Hi_D)'], seealso: ['idwt', 'wavedec'] },
    wavedec: { summary: 'Multilevel 1-D wavelet decomposition', syntax: ['[c,l] = wavedec(x,n,wname)', '[c,l] = wavedec(x,n,LoD,HiD)', '[c,l] = wavedec(___,Mode=extmode)'], seealso: ['waverec', 'dwt', 'detcoef'], description: ['[c,l] = wavedec(x,n,wname) returns the wavelet decomposition of the 1-D signal x at level n using the wavelet wname. The output decomposition structure consists of the wavelet decomposition vector c and the bookkeeping vector l, which is used to parse c.', '[c,l] = wavedec(x,n,LoD,HiD) returns the wavelet decomposition using the specified lowpass and highpass wavelet decomposition filters LoD and HiD, respectively.', '[c,l] = wavedec(___,Mode=extmode) uses the specified discrete wavelet transform (DWT) extension mode extmode. This syntax can be used with either of the previous syntaxes.'] },
    haart: { summary: '1-D Haar discrete wavelet transform', syntax: ['[a,d] = haart(x)', '[a,d] = haart(x,level)', '[a,d] = haart(x,level,integerflag)'], seealso: ['ihaart', 'ihaart2', 'haart2'], description: ['[a,d] = haart(x) performs the 1-D Haar discrete wavelet transform of the even-length vector, x. The input x can be univariate or multivariate data. If x is a matrix, haart operates on each column of x. If the length of x is a power of 2, the Haar transform is obtained down to level log2(length(x)). Otherwise, the Haar transform is obtained down to level floor(log2(length(x)/2)).', '[a,d] = haart(x,level) obtains the Haar transform down to the specified level.', '[a,d] = haart(___,integerflag) specifies how the Haar transform handles integer-valued data, using any of the previous syntaxes.'] },
    ihaart2: { summary: 'Inverse 2-D Haar discrete wavelet transform', syntax: ['xrec = ihaart2(a,h,v,d)', 'xrec = ihaart2(a,h,v,d,level)', 'xrec = ihaart2(___,integerflag)'], seealso: ['haart', 'ihaart', 'haart2'], description: ['xrec = ihaart2(a,h,v,d) returns the inverse 2-D Haar transform, xrec, for the approximation coefficients, a, and the horizontal, vertical, and diagonal detail coefficients, h, v, and d. All the inputs, a, h, v, and d, are outputs of haart2.', 'xrec = ihaart2(a,h,v,d,level) returns the inverse 2-D Haar transform at the specified level.', 'xrec = ihaart2(___,integerflag) specifies how the inverse 2-D Haar transform handles integer-valued data, using any of the previous syntaxes.'] },
    detcoef: { summary: 'Extract detail coefficients from wavelet decomposition', syntax: ['D = detcoef(C,L)', 'D = detcoef(C,L,N)', 'D = detcoef(C,L,N,"cells")'], seealso: ['appcoef', 'wavedec'], description: ['D = detcoef(C,L) extracts the detail coefficients at the coarsest scale from the wavelet decomposition structure [C, L]. See wavedec for more information on C and L.', 'D = detcoef(C,L,N) extracts the detail coefficients at the level or levels specified by N.', 'D = detcoef(C,L,N,"cells") returns a cell array containing the detail coefficients. A minimum of two levels must be specified. The _i_ th element of D contains the detail coefficients at the _i_ th specified level.', '* If length(N)>1, the D = detcoef(C,L,N) is equivalent to D = detcoef(C,L,N,"cells").', '* D = detcoef(C,L,"cells") is equivalent to D = detcoef(C,L,[1:NMAX]), where NMAX = length(L)-2.'] },
    dyaddown: { summary: 'Dyadic downsampling', syntax: ['Y = dyaddown(X)', 'Y = dyaddown(X,EVENODD)', "Y = dyaddown(___,'type')"], seealso: ['dyadup'], description: ['Y = dyaddown(X) downsamples even-indexed elements of X. Y contains even-index samples of X in this case. Specify X as a vector or matrix. When you specify X as a vector, the function returns a version of X downsampled by 2.', 'Y = dyaddown(X,EVENODD) downsamples even- or odd-indexed elements of X. Y can contain even- or odd-indexed samples of X depends on the value of EVENODD. Specify X as a vector. When you specify X as a vector, the function returns a version of X downsampled by 2.', 'Y = dyaddown(___,\'type\') returns a version of X obtained by suppressing columns or rows, or rows and columns of X using \'type\' argument. Specify X as a matrix.'] },
    qorthwavf: { summary: 'Kingsbury Q-shift filters for complex dual-tree transform', syntax: ['[LoDa,LoDb,HiDa,HiDb,LoRa,LoRb,HiRa,HiRb] = qorthwavf(num)'], seealso: ['qbiorthfilt', 'dualtree'], description: ['[LoDa,LoDb,HiDa,HiDb,LoRa,LoRb,HiRa,HiRb] = qorthwavf(num) returns the Kingsbury Q-shift filters for the Q-shift complex dual-tree transform. The integer num refers to the number of nonzero coefficients (taps) in the filter. Valid options for num are 6, 10, 14, 16, and 18. All filters are of even lengths and the tree B filters are the time reverse of the tree A filters.'] },
    biorwavf: { summary: 'Biorthogonal wavelet filter pair (reconstruction and decomposition)', syntax: ['[RF,DF] = biorwavf(wname)'], seealso: ['biorfilt', 'waveinfo'], description: ['[RF,DF] = biorwavf(wname) returns the reconstruction (synthesis) and decomposition (analysis) scaling filters, RF and DF, respectively, associated with the biorthogonal wavelet specified by wname.'] },
    biorfilt: { summary: 'Biorthogonal wavelet filters (four-filter bank)', syntax: ['[LoD,HiD,LoR,HiR] = biorfilt(DF,RF)', "[LoD1,HiD1,LoR1,HiR1,LoD2,HiD2,LoR2,HiR2] = biorfilt(DF,RF,'8')"], seealso: ['biorwavf', 'orthfilt'], description: ['[LoD,HiD,LoR,HiR] = biorfilt(DF,RF) returns four filters associated with the biorthogonal wavelet specified by decomposition filter DF and reconstruction filter RF. These filters are', '* LoD — Decomposition lowpass filter', '* HiD — Decomposition highpass filter', '* LoR — Reconstruction lowpass filter', '* HiR — Reconstruction highpass filter'] },
  };
