// Help entries for the Simulink, extracted from simulink.ts.
// Keyed by function name; consumed via ToolboxModule.help (see tb/types.ts).
import type { HelpEntry } from './types';

export const HELP_SIMULINK: Record<string, HelpEntry | string> = {
    new_system: { summary: 'Create a new Simulink model in memory', syntax: ["new_system('modelname')"], seealso: ['open_system', 'save_system', 'add_block'], description: ['h = new_system creates a model named untitled (and then untitled1, untitled2, and so on) based on your default model template and returns the new model’s numeric handle. Select your default model template on the Simulink® start page or by using the Simulink.defaultModelTemplate function.', 'The new_system function does not open the new model. This function creates the model in memory. To save the model, use save_system, or open the model with open_system and then save it using the Simulink Editor.', 'h = new_system(name) creates a model based on your default model template and gives the new model the specified name. This function returns the new model’s numeric handle. Select your default model template on the Simulink start page or by using the Simulink.defaultModelTemplate function.', 'To avoid shadowing, if name is empty, the new_system function checks loaded models and files on the path and creates a model with the next available name untitled, untitled1, untitled2, and so on.', 'The new_system function does not open the new model. This function creates the model in memory. To save the model, use save_system, or open the model with open_system and then save it using the Simulink Editor.'] },
    add_block: { summary: 'Add a block to a Simulink model', syntax: ["add_block('srcblock','dstblock')"], seealso: ['add_line', 'set_param', 'new_system'], description: ['h = add_block(source,dest) adds a copy of the block specified by source to the destination specified by dest. The new block is added at the same position in the block diagram as the source block appears in its parent block diagram.', 'The destination model must be loaded.', 'h = add_block(___,Name=Value) specifies options using one or more name- value arguments in addition to the input arguments in the previous syntax. For example, to add a Gain block that multiplies the input by 5, set Gain to "5".'] },
    add_line: { summary: 'Connect block ports with a signal line', syntax: ["add_line('model','srcblock/port','dstblock/port')"], seealso: ['add_block', 'delete_line', 'set_param'], description: ['h = add_line(sys,out,in) adds a line in the model or subsystem sys that connects one block\'s output port out to another block\'s input port in. The ports must be unconnected and compatible. Both ports must be in the same location in the model hierarchy, either at the top level or in the same model component. This syntax draws the most direct route from port to port, for example, diagonal lines or lines that go through other blocks.', 'h = add_line(sys,out,in,\'autorouting\',autoOption) connects blocks, specifying whether to route the lines around other blocks.', 'h = add_line(sys,points) adds a line drawn by (x,y) coordinate points relative to the upper-left corner of the Simulink® Editor canvas before any canvas resizing. If either end of the line is within five pixels of a corresponding port, the function connects the line to it. The line can have multiple segments.'] },
    set_param: { summary: 'Set a block or model parameter', syntax: ["set_param('obj','param',value)"], description: ["set_param('model/block','param',value) sets a named parameter on a Simulink block or model, e.g. set_param('model','StopTime','10')."], seealso: ['get_param', 'add_block', 'sim'] },
    get_param: { summary: 'Get a block or model parameter', syntax: ["val = get_param('obj','param')"], seealso: ['set_param', 'add_block'], description: ['value = get_param(object,parameter) returns the value value of the specified parameter parameter for the target object specified by object. The target object can be a model, subsystem, library, block, line, port, or bus element port element specified as a path or a handle.', 'Open or load the related Simulink® model, subsystem, or library before calling this function.'] },
    sim: { summary: 'Simulate a Simulink model', syntax: ["simout = sim('model')", "simout = sim('model',Name,Value)"], description: ["simout = sim('model') runs the Simulink model named 'model' and returns a Simulink.SimulationOutput object containing logged signals.", 'Name-Value options include StopTime, SimulationMode, and SaveOutput.'], seealso: ['set_param', 'get_param', 'new_system'] },
  };
